appname = casdoor # 应用程序名称，目前没有实际用途
httpport = 8000 # 监听端口
runmode = dev  # dev or prod
copyrequestbody = true # 

driverName = mysql
dataSourceName = root:123456@tcp(localhost:3306)/
dbName = casdoor
tableNamePrefix =  # 适配器表的前缀
showSql = false  # 如果日志级别大于INFO，是否在日志中显示SQL语句

redisEndpoint = # redis.example.com:6379,db,password Beego用于Session存储，如果参数为空，会话数据将作为文件在./tmp文件夹中本地存储
defaultStorageProvider = # 默认的文件存储服务名称
isCloudIntranet = false # 识别提供者是否为内网
authState = "casdoor" # 授权应用程序名称
socks5Proxy = "127.0.0.1:10808" # Socks代理服务IP地址，绕过防火墙访问Google,Facebook,LinkedIn,Steam
verificationCodeTimeout = 10  # 设置验证码的过期时间，过期后，用户需要再次获取
initScore = 0 # 每个用户的最初分数
logPostOnly = true # 确定是否使用post方法添加记录
isUsernameLowered = false # 
origin = # origin形式的后端域名
originFrontend = # 
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100 
enableErrorMask = false
enableGzip = true # 在请求头包含Accept-Encoding=gzip接受gzip编码进行相应
inactiveTimeoutMinutes = # 设置不活动的最长分钟数，如果不活动时间达到此值，casdoor将注销该用户
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "built-in"
radiusSecret = "secret"
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"adapter":"file", "filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
initDataNewOnly = false
initDataFile = "./init_data.json"
frontendBaseDir = "../cc_0"